// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt4LmOEyuxwNhuSqJse7ZD3hMhI5_ySmQ',
    appId: '1:181785269437:web:b5e823b3278e230ebdd3d4',
    messagingSenderId: '181785269437',
    projectId: 'hydrosenseproj',
    authDomain: 'hydrosenseproj.firebaseapp.com',
    storageBucket: 'hydrosenseproj.firebasestorage.app',
    measurementId: 'G-7SGFZP5CZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0GLKGHG7Q0dui5Pmdnug4ODB1XP1AHrA',
    appId: '1:181785269437:android:5edea9032ca41c2ebdd3d4',
    messagingSenderId: '181785269437',
    projectId: 'hydrosenseproj',
    storageBucket: 'hydrosenseproj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgqufIKDEiAepFiw5QSzxQ85oI5pI4ll0',
    appId: '1:181785269437:ios:49cbb0d91e293b2fbdd3d4',
    messagingSenderId: '181785269437',
    projectId: 'hydrosenseproj',
    storageBucket: 'hydrosenseproj.firebasestorage.app',
    iosBundleId: 'com.example.hydrosensenew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgqufIKDEiAepFiw5QSzxQ85oI5pI4ll0',
    appId: '1:181785269437:ios:49cbb0d91e293b2fbdd3d4',
    messagingSenderId: '181785269437',
    projectId: 'hydrosenseproj',
    storageBucket: 'hydrosenseproj.firebasestorage.app',
    iosBundleId: 'com.example.hydrosensenew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt4LmOEyuxwNhuSqJse7ZD3hMhI5_ySmQ',
    appId: '1:181785269437:web:1126f5ea47e258f1bdd3d4',
    messagingSenderId: '181785269437',
    projectId: 'hydrosenseproj',
    authDomain: 'hydrosenseproj.firebaseapp.com',
    storageBucket: 'hydrosenseproj.firebasestorage.app',
    measurementId: 'G-F0J1QMNZX4',
  );

 }